= jcli
:nofooter:

Sugared wrappers to execute methods from JDK and JVM-based libraries from the command line.

E.g., To generate a UUID, java.util.UUID contains a method, `UUID.randomUUID()`. The command line generated by this source code helps you to execute that method by simply invoking `jcli util -uuid`.

== Motivation
The goal is to expose the wealth of utility methods available in the JVM ecosystem right at the command line, so that simple tasks do not require users to setup a Java project with relevant dependencies, or to write a Main method that does what is needed.

It is also intended that this be a GraalVM-compatible project so that distributions do not require the end user to do a JVM setup with some compatible Java version.

Most methods return a single result, and so can be used in pipe operations combined with other command line utilities if needed.

== Available Commands

In order to view better results, it is simpler to run the help for a command or sub-command.

E.g., `jcli time -help`
```
Usage: jcli time [-hV] [-now] [-toEpochMilli]
Methods from java.time
  -h, --help        Show this help message and exit.
      -now, --now   Prints the value of Instant.now()
      -toEpochMilli, --toEpochMilli, -toEpochMillis, --toEpochMillis
                    Prints the value of Instant.now().toEpochMillis()
  -V, --version     Print version information and exit.
```

Here is a small sample of available options.

[cols="1,1,1,1"]
|===
|SubCommand | Options | Description | Usage

|util
|_-uuid_
|Generates a UUID
|`jcli util -uuid`

|time
|_-now_
|Prints the value of current time as standard formatted date/time
|`jcli time -now`

|time
|_-toEpochMilli_
|Prints the value of current time as the number of milliseconds from the epoch of 1970-01-01T00:00:00Z.
|`jcli time -toEpochMilli`
|===

== Build

To build this project's source code:

. Clone this project
. At the root of the project, execute `./gradlew clean build`
. The build generates a jar at `build/libs`. To execute the cli app, run `java -jar build/libs/jcli-0.1-all.jar -h` to view the help manual.
. Or, create an alias like this. `alias jcli='java -jar build/libs/jcli-0.1-all.jar'`
Then run, `jcli -h`.